jni com_android_adservices libhpke_jni.so:libtflite_support_classifiers_native.so
jni com_android_appsearch libappsearchservice.so:libicing_anywhere.so
jni com_android_art libartservice.so
public com_android_art libnativehelper.so
jni com_android_conscrypt libjavacrypto.so
public com_android_i18n libicui18n.so:libicuuc.so:libicu.so
jni com_android_mediaprovider libpdfclient.so
public com_android_neuralnetworks libneuralnetworks.so
jni com_android_ondevicepersonalization libfcp_cpp_dep_jni.so:libfcp_hpke_jni.so
jni com_android_os_statsd libstats_jni.so
jni com_android_tethering libandroid_net_connectivity_com_android_net_module_util_jni.so:libandroid_net_connectivity_com_android_net_module_util_jni_CommonConnectivityJni.so:libframework-connectivity-jni.so:libframework-connectivity-tiramisu-jni.so:libmainlinecronet.141.0.7340.3.so:libservice-connectivity.so:libservice-thread-jni.so:stable_cronet_libcrypto.so:stable_cronet_libssl.so
jni com_android_uwb libuwb_uci_jni_rust.so
jni com_android_virt libvirtualizationservice_jni.so:libvirtualmachine_jni.so
jni com_android_wifi libservice-wifi-jni.soname: Trigger Termux Library Builds on Jitpack

on:
  release:
    types:
      - published

jobs:
  trigger-termux-library-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Set vars
        run: echo "TERMUX_LIB_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV # Do not include "v" prefix
      - name: Echo release
        run: echo "Triggering termux library builds on jitpack for '$TERMUX_LIB_VERSION' release after waiting for 3 mins"
      - name: Trigger termux library builds on jitpack
        run: |
          sleep 180 # It will take some time for the new tag to be detected by Jitpack
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/terminal-emulator/$TERMUX_LIB_VERSION/terminal-emulator-$TERMUX_LIB_VERSION.pom"
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/terminal-view/$TERMUX_LIB_VERSION/terminal-view-$TERMUX_LIB_VERSION.pom"
          curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/termux-shared/$TERMUX_LIB_VERSION/termux-shared-$TERMUX_LIB_VERSION.pom"
